-- :help options
vim.opt.backup = false            -- creates a backup file
vim.opt.clipboard = "unnamedplus" -- uses the system clipboard
vim.opt.cmdheight = 2             -- more space in cmdline for messages
vim.opt.completeopt = { "menuone", "noselect" } -- cmp stuff
vim.opt.conceallevel = 0          -- makes `` visible in markdown
vim.opt.fileencoding = "utf-8"    -- file encoding
vim.opt.hlsearch = true           -- hilight last search query
vim.opt.ignorecase = true         -- case sensitivity in search
vim.opt.mouse = "a"               -- allows sacrilege
vim.opt.pumheight = 10            -- pop up menu height
vim.opt.showmode = true           -- shows current editing mode
vim.opt.showtabline = 2           -- always show tabs
vim.opt.smartcase = true          -- case-sensitive when search has caps
vim.opt.smartindent = true        -- hope it doesn't fuck me over
vim.opt.splitbelow = true         -- hsplit goes down, not up
vim.opt.splitright = false        -- vsplit goes right, not left
vim.opt.swapfile = false          -- create a swapfile while editing
-- vim.opt.termguicolors = true     -- set term gui colors (well supported)
vim.opt.timeoutlen = 200          -- leader timeout in msec
vim.opt.undofile = true           -- persistent undo file
vim.opt.updatetime = 200          -- faster completion (400ms default)
vim.opt.writebackup = false       -- when a file is open by other program
vim.opt.expandtab = false         -- auto turn tabs to spaces
vim.opt.shiftwidth = 4            -- charcount of "one indentation"
vim.opt.tabstop = 4               -- spaces to insert for a tab with et
vim.opt.cursorline = true         -- underline the whole line at cursor
vim.opt.number = true             -- show the line number in the gutter
vim.opt.relativenumber = true     -- show line numbers as offset from cursor
vim.opt.numberwidth = 4           -- width of numberline gutter (default 4)
vim.opt.signcolumn = "yes"        -- always show the sign column
vim.opt.wrap = true               -- word-wrap long lines
vim.opt.scrolloff = 4             -- top/bottom line margin from cursor
vim.opt.sidescrolloff = 8         -- horizontal margin from cursor (no wrap)
vim.opt.shortmess = "a"           -- how to display messages in the msg line
vim.opt.guifont = "firacode:h12"  -- font to use in graphical nvim frontends
vim.opt.list = true
vim.opt.listchars = "tab:→ ,lead:·,trail:¶"
vim.opt.formatoptions = "n2ljp"   -- magic!
vim.opt.iskeyword:append "-"      -- add '-' to iskeyword chars
